#!/bin/bash
#SBATCH -J runcoloc
#SBATCH -A CWALLACE-SL2-CPU
#SBATCH --nodes 1
#SBATCH --ntasks 15
#SBATCH --time 04:40:00
#SBATCH --mail-type FAIL
#SBATCH -p icelake-himem
#SBATCH --output=./err/%A.err
shopt -s nullglob
. /etc/profile.d/modules.sh # Leave this line (enables the module command)
module purge                # Removes all modules still loaded
#module load default-impi    # REQUIRED - loads the basic environment
module load rhel8/default-icl             # REQUIRED - loads the basic environment
#module load r-4.0.2-gcc-5.4.0-xyx46xb      # More recent R (4.1.3) has X11 disabled and throws an error, which is unfortunate. This version has X11 available, so we'll use it.
export I_MPI_PIN_ORDER=scatter # Adjacent domains have minimal sharing of caches/sockets
JOBID=$SLURM_JOB_ID
echo -e "JobID: $JOBID"
# G=$SLURM_ARRAY_TASK_ID ### this is the array variable, you can use it the way you want. In this example I use it to select the gene based on the line number in a file

Rscript --vanilla run-coloc-driver-snps.R





